import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* create container  */}
        <div className="container mx-auto px-4">
          {/* create header  */}
          <header className="flex justify-between items-center py-4">
            <h1 className="text-2xl font-semibold">
              <a href="https://nextjs.org">Next.js</a>
            </h1>
            <nav>
              <ul className="flex space-x-4">
                <li>
                  <a href="https://nextjs.org/docs">Docs</a>
                </li>
                <li>
                  <a href="https://nextjs.org/learn">Learn</a>
                </li>
                <li></li>
              </ul>
            </nav>
          </header>
          {/* create main  */}
          <main>{children}</main>
          {/* create footer  */}
          <footer className="py-4 flex justify-center items-center">
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className="flex justify-center items-center space-x-2"
            >
              <span>Powered by</span>
              <img src="/vercel.svg" alt="Vercel Logo" className="h-4" />
            </a>
          </footer>
        </div>
      </body>
    </html>
  );
}
